# NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Library documentation: <a>http://www.numpy.org/</a>

In [1]:
import numpy as np

# Task 1: declare a vector using a list as the argument

In [4]:
three_d_vector = np.array([1,2,3])
three_d_vector

array([1, 2, 3])

# Task 2: declare a matrix using a nested list as the argument

In [6]:
matrix_example = np.array([[1,2,3],[4,5,6]])
matrix_example

array([[1, 2, 3],
       [4, 5, 6]])

# Task 3: initialize x or x and y using the following functions: arange, linspace, logspace, mgrid

In [24]:
x_arange = np.arange(1,10,2)
print "Numpy arange (1,10) with step size 2:"
print x_arange
x_linspace = np.linspace(1,10,2)
print "Numpy linspace (uniform) with step size 2:"
print x_linspace
x_logspace = np.logspace(1,10,20, endpoint=True)
print "Numpy logspace with endpoint True:"
print x_logspace
x_mgrid = np.mgrid[0:5, 0:5]
print "Numpy mgrid (return mesh grid)"
print x_mgrid

Numpy arange (1,10) with step size 2:
[1 3 5 7 9]
Numpy linspace (uniform) with step size 2:
[  1.  10.]
Numpy logspace with endpoint True:
[  1.00000000e+01   2.97635144e+01   8.85866790e+01   2.63665090e+02
   7.84759970e+02   2.33572147e+03   6.95192796e+03   2.06913808e+04
   6.15848211e+04   1.83298071e+05   5.45559478e+05   1.62377674e+06
   4.83293024e+06   1.43844989e+07   4.28133240e+07   1.27427499e+08
   3.79269019e+08   1.12883789e+09   3.35981829e+09   1.00000000e+10]
Numpy mgrid (return mesh grid)
[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]


In [25]:
from numpy import random

# Task 4: what is difference between random.rand and random.randn

* random.rand returns random values given specific shape from uniform distribution
* random.randn returns a sample from a standard normal distribution

# Task 5: what are the funciotns diag, itemsize, nbytes and ndim about?

* diag returns a diagonal array from a matrix
* itemsize returns the item size of ndarray
* nbytes returns total bytes consumed by a particular numpy array
* ndim returns the number of array dimensions

In [30]:
# assign new value
M = np.array([[1,2,3],[4,5,6]])
M[0,0] = 7

In [31]:
M[0,:] = 0

In [33]:
# slicing works just like with lists
A = np.array([1,2,3,4,5])
A[1:3]

array([2, 3])

# Task 6: Using list comprehensions create the following matrix
array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [35]:
A = np.array([[ 0, 1, 2, 3, 4],
              [10, 11, 12, 13, 14],
              [20, 21, 22, 23, 24],
              [30, 31, 32, 33, 34],
              [40, 41, 42, 43, 44]])

In [36]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [39]:
# index masking
B = np.array([n for n in range(5)])
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

### Linear Algebra

In [42]:
v1 = np.arange(0, 5)

In [43]:
v1 + 2

array([2, 3, 4, 5, 6])

In [44]:
v1 * 2

array([0, 2, 4, 6, 8])

In [45]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [46]:
np.dot(v1, v1)

30

In [47]:
np.dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [48]:
# cast changes behavior of + - * etc. to use matrix algebra
M = np.matrix(A)
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [51]:
# inner product
v1.T * v1

array([ 0,  1,  4,  9, 16])

In [55]:
C = np.matrix([[1j, 2j], [3j, 4j]])
C

matrix([[ 0.+1.j,  0.+2.j],
        [ 0.+3.j,  0.+4.j]])

In [56]:
np.conjugate(C)

matrix([[ 0.-1.j,  0.-2.j],
        [ 0.-3.j,  0.-4.j]])

In [57]:
# inverse
C.I

matrix([[ 0.+2.j ,  0.-1.j ],
        [ 0.-1.5j,  0.+0.5j]])

### Statistics

In [58]:
np.mean(A[:,3])

23.0

In [60]:
np.std(A[:,3]), np.var(A[:,3])

(14.142135623730951, 200.0)

In [61]:
A[:,3].min(), A[:,3].max()

(3, 43)

In [63]:
d = np.arange(1, 10)
np.sum(d), np.prod(d)

(45, 362880)

In [64]:
np.cumsum(d)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [65]:
np.cumprod(d)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [66]:
# sum of diagonal
np.trace(A)

110

In [67]:
m = np.random.rand(3, 3)

In [68]:
# use axis parameter to specify how function behaves
m.max(), m.max(axis=0)

(0.87468241317501216, array([ 0.6890535 ,  0.87468241,  0.81414742]))

In [69]:
# reshape without copying underlying data
n, m = A.shape
B = A.reshape((1,n*m))

In [70]:
# modify the array
B[0,0:5] = 5

In [71]:
# also changed
A

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [72]:
# creates a copy
B = A.flatten()

In [87]:
# can insert a dimension in an array
newaxis = 0
v = np.array([1,2,3])
#v[:, newaxis], v[:,newaxis].shape, v[newaxis,:].shape

In [80]:
np.repeat(v1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [81]:
np.tile(v1, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [82]:
w = np.array([5, 6])

In [83]:
np.concatenate((v, w), axis=0)

array([1, 2, 3, 5, 6])

In [84]:
# deep copy
B = np.copy(A)